# Generated by Django 5.2.15 on 2026-06-22 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='review',
            new_name='reservation',
        ),
    ]
