# Generated by Django 5.2.15 on 2026-06-27 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0002_rename_review_review_reservation'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='baseschedule',
            unique_together={('court', 'start_time')},
        ),
        migrations.RemoveField(
            model_name='baseschedule',
            name='weekday',
        ),
    ]
